return PlaceObj('ModDef', {
	'title', "Funded Casino",
	'description', "Colonists gamble their funding at casinos, so long as you have the capital to cover the bets. The house may always win, but beware genius colonists! https://github.com/Surviving-Mars-Mods/Funded-Casino",
	'image', "cover.png",
	'last_changes', "https://github.com/Surviving-Mars-Mods/Funded-Casino/blob/main/Info/changelog.md",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"src/*",
		"*.iml",
		".idea/*",
	},
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "FIZZLE1",
			'title', "Fizzle Fuze's Library",
			'version_major', 1,
			'version_minor', 7,
		}),
	},
	'id', "FIZZLE13",
	'steam_id', "2705200418",
	'pops_desktop_uuid', "80ffea15-da89-4d68-9b60-4149ee4e3f96",
	'pops_any_uuid', "a32cc3f5-a850-40a0-93fa-afd1d3fefea7",
	'author', "Fizzle Fuze",
	'version_major', 1,
	'version_minor', 7,
	'version', 41235,
	'lua_revision', 1009413,
	'saved_with_revision', 1010838,
	'has_options', true,
	'saved', 1650593618,
	'TagBuildings', true,
	'code', {
		"Code/BuildingTemplate.lua",
		"Code/Code.lua",
		"Code/FundedCasino.lua",
	},
})