return PlaceObj('ModDef', {
	'title', "Funded Casino",
	'description', "Colonists gamble their funding at casinos, so long as you have the capital to cover the bets. The house may always win, but beware genius colonists! <3 Fiz",
	'image', "cover.png",
	'last_changes', "bugfixes",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"src/*",
		"*.txt",
		"*.iml",
		".idea/*",
	},
	'id', "tmtk2Rd",
	'steam_id', "2705200418",
	'pops_desktop_uuid', "80ffea15-da89-4d68-9b60-4149ee4e3f96",
	'pops_any_uuid', "a32cc3f5-a850-40a0-93fa-afd1d3fefea7",
	'author', "Fizzle Fuze",
	'version_major', 1,
	'version_minor', 6,
	'version', 77,
	'lua_revision', 1009413,
	'saved_with_revision', 1010838,
	'code', {
		"Code/CasinoProfit.lua",
		"Code/FundedCasino.lua",
	},
	'has_options', true,
	'saved', 1650553838,
	'TagBuildings', true,
})